[ids]
*

[main]
# Compose zu Pos1 bleibt hier, da es eine einfache Umbelegung ist
compose = home
# Tab Overload: halten -> Maus-Keypad-Layer, tippen -> normales Tab
tab = overload(mouse_keys, tab)
# Caps-Lock Overload: Beim Halten aktiviert es den Layer "caps_vim",
# beim einmaligen Tippen sendet es "escape"
capslock = overload(caps_vim, escape)
[control]
# Wenn Strg gehalten wird, soll die Home-Taste zu Ende werden
compose = end
# sondern fügen dem existierenden Meta-Layer neue Funktionen hinzu.
[meta]
a = M-5
s = M-6
e = M-3
f = M-8
c = M-9
x = C-A-f3
z = C-A-f2

[caps_vim]
# --- 1. NAVIGATION & SPEZIAL ---
h = left
j = down
k = up
l = right
enter = escape
compose = end
backspace = C-backspace
# --- 2. DAS KOMPLETTE ALPHABET (ZU STRG + TASTE) ---
slash = C-slash
rightbrace = C-rightbrace
f1 = C-f1
f2 = C-f2
a = C-a
b = C-b
c = C-c
d = C-d
e = C-e
f = C-f
g = C-g
# h, j, k, l sind oben als Pfeiltasten definiert
i = C-i
m = C-m
n = C-n
o = C-o
p = C-p
q = C-q
r = C-r
s = C-s
t = C-t
u = C-u
v = C-v
w = C-w
x = C-x
y = C-y
z = C-z
tab = C-tab
# --- 3. DEUTSCHE UMLAUTE (Zusatz für deutsche Tastaturen) ---
# DELETED
# --- 4. ZAHLENREIHE ALS F-TASTEN ---
1 = C-1
2 = C-2
3 = C-3
4 = C-4
5 = C-5
6 = C-6
7 = C-7
8 = C-8
9 = C-9
escape = C-escape

[mouse_keys]
# Vim-Richtungen auf Numpad (für Accessibility Mouse Keys)
h = kp4
j = kp2
k = kp8
l = kp6

# Klicks
y = leftmouse
u = rightmouse
